services:

  vote:
    image: voting-app:v1
    build:
      context: ./app/vote
      target: dev

    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

    volumes:
      - ./app/vote:/usr/local/app

    ports:
      - "8082:80"

    networks:
      - front-tier
      - back-tier


  result:
    image: result-app:v1
    build: ./app/result

    entrypoint: nodemon --inspect=0.0.0.0 server.js

    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

    volumes:
      - ./app/result:/usr/local/app

    ports:
      - "8081:80"
      - "127.0.0.1:9229:9229"

    networks:
      - front-tier
      - back-tier


  worker:
    image: worker-app:v1
    build:
      context: ./app/worker

    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

    networks:
      - back-tier


  redis:
    image: redis:alpine

    volumes:
      - "./app/healthchecks:/healthchecks"

    healthcheck:
      test: ["CMD-SHELL", "/healthchecks/redis.sh"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - back-tier


  db:
    image: postgres:15-alpine

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./app/healthchecks:/healthchecks"

    healthcheck:
      test: ["CMD-SHELL", "/healthchecks/postgres.sh"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - back-tier


  seed:
    image: seed-app:v1
    build: ./app/seed-data

    profiles:
      - seed

    depends_on:
      vote:
        condition: service_healthy

    networks:
      - front-tier

    restart: "no"


volumes:
  db-data:


networks:
  front-tier:
  back-tier: